export const REQUEST = 'REQUEST';
export const LOGIN = '[AUTH] LOGIN';
export const LOGIN_SUCCESS = '[AUTH] LOGIN_SUCCESS';
export const LOGIN_FAILED = '[AUTH] LOGIN_FAILED';
export const LOGOUT = '[AUTH] LOGOUT';
export const REGISTER = '[AUTH] REGISTER';
export const REGISTER_SUCCESS = '[AUTH] REGISTER_SUCCESS';
export const REGISTER_FAILED = '[AUTH] REGISTER_FAILED';
export const ERROR = '[AUTH] ERROR';

export const AUTH_REQUEST = 'REQUEST';
export const AUTH_LOGIN = 'LOGIN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGIN_FAILED = 'LOGIN_FAILED';
export const AUTH_LOGOUT = 'LOGOUT';
export const AUTH_REGISTER = 'REGISTER';
export const AUTH_REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILED = 'REGISTER_FAILED';
export const AUTH_ERROR = 'ERROR';
